{
 "title": "hw3",
 "time": { "from": "2021-05-02T12:40:00.000Z", "to": "2021-05-02T13:20:59.000Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU+Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container!=\"POD\", cluster=\"$cluster\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container!=\"POD\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "RPS+Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "RPS (app)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_request_count_total{exported_endpoint=\"/db\"}[1m]))"
    }
   ]
  },
  {
   "title": "RPS (nginx)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_request_duration_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Latency 0.5 (app)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(app_request_latency_seconds_bucket{exported_endpoint=\"/db\"}[1m])))*1000"
    }
   ]
  },
  {
   "title": "Latency 0.5 (nginx)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))*1000"
    }
   ]
  },
  {
   "title": "Latency 0.9 (app)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(app_request_latency_seconds_bucket{exported_endpoint=\"/db\"}[1m])))*1000"
    }
   ]
  },
  {
   "title": "Latency 0.9 (nginx)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))*1000"
    }
   ]
  },
  {
   "title": "Latency 0.99 (app)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(app_request_latency_seconds_bucket{exported_endpoint=\"/db\"}[1m])))*1000"
    }
   ]
  },
  {
   "title": "Latency 0.99 (nginx)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))*1000"
    }
   ]
  },
  {
   "title": "Error Rate (nginx)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(nginx_ingress_controller_request_duration_seconds_count{status=\"500\"}[1m])"
    }
   ]
  }
 ]
}